### PR TITLE
civo: add ascii logo

### PR DESCRIPTION
**Pull request by shivarm**

### CODE REVIEW

**Comment by shivarm** [comment]
review\ @alejandrojnm @saiyam1814 @vishalanarase

**Review by alessandroargentieri — COMMENTED** [review]
if you straighten the word (now it's not well formatted) and write Civo CLI I'll approve and merge. Thanks for the nice idea.

**Comment by shivarm** [comment]
@alessandroargentieri can we merge it?

**Comment by alessandroargentieri** [comment]
@shivam-sharma7 I see the label is not well formatted. This is the last version you proposed:
```bash
~/tests/cli_test/cli (⌥ ascii-art-logo) $ go run main.go version --verbose

	   _____  _                  _____  _       _____ 
  / ____|(_)                / ____|| |     |_   _|
 | |      _ __   __  ___   | |     | |       | |  
 | |     | |\ \ / / / _ \  | |     | |       | |  
 | |____ | | \ V / | (_) | | |____ | |____  _| |_ 
  \_____||_|  \_/   \___/   \_____||______||_____|
```

**Review by alessandroargentieri — CHANGES_REQUESTED** [review]
first line is completely shifted

**Comment by shivarm** [comment]
@alessandroargentieri formattted

**Comment by alessandroargentieri** [comment]
@shivam-sharma7 may you paste what you're getting? After pulling your branch is still unformatted from my side...

**Comment by shivarm** [comment]
> @shivam-sharma7 may you paste what you're getting? After pulling your branch is still unformatted from my side...

please check again.

**Review by alessandroargentieri — APPROVED** [review]
LGTM

**Pull request merged**
