### PR TITLE
Changed LICENSE File

### PR DESCRIPTION
**Pull request by SaptarshiSarkar12**
I found that the repository contains Apache License but the Readme mentions about MIT. So, I changed it to MIT License instead of Apache.

### CODE REVIEW

**Comment by SaptarshiSarkar12** [comment]
@alejandrojnm @saiyam1814 
Please review this PR.

**Comment by alessandroargentieri** [comment]
You tried to change the LINCENSE in place of the README. Please do the opposite thing @SaptarshiSarkar12

**Comment by SaptarshiSarkar12** [comment]
@alessandroargentieri please re-review this PR

**Review by alessandroargentieri — APPROVED** [review]
LGTM

**Pull request merged**
