### PR TITLE
Add Support for DB version list

### PR DESCRIPTION
**Pull request by uzaxirr**
Screenshot 2024-02-24 at 2 17 49 AM

### CODE REVIEW

**Comment by alejandrojnm** [comment]
Nice, Why did you remove the utility `EnsureCurrentRegion` ?

**Comment by uzaxirr** [comment]
> Nice, Why did you remove the utility `EnsureCurrentRegion` ?

That's bcz db versions are independent of regions and irrespective of the region the response from API will always be the same.

**Comment by alejandrojnm** [comment]
The API reads the version from the backend (region), so that means we can have different versions per region, any way you can confirm this with @alessandroargentieri

**Comment by alessandroargentieri** [comment]
Yes, it depends from the region. So the region must be passed to the api call like we do for any civo resource

**Comment by uzaxirr** [comment]
Done, made the required changes.

**Review by alessandroargentieri — APPROVED** [review]
LGTM

**Pull request merged**
