### PR TITLE
Cmd to Describe network

### PR DESCRIPTION
**Pull request by uzaxirr**
Screenshot 2024-04-02 at 11 41 08 PM

### CODE REVIEW

**Comment by alessandroargentieri** [comment]
Maybe a format like the one for kubernetes would be better since the number of parameters to be shown is high and variable (gateway_id, vlan_id, harware_addr are missing)

**Comment by alejandrojnm** [comment]
@alessandroargentieri or @uzaxirr  we have `(gateway_id, vlan_id, harware_addr)` in the network ??

**Comment by alessandroargentieri** [comment]
Yes we have. All these params are optional

**Comment by uzaxirr** [comment]
> Maybe a format like the one for kubernetes would be better since the number of parameters to be shown is high and variable (gateway_id, vlan_id, harware_addr are missing)

`gateway_id`, `vlan_id`, `harware_addr` are visible when vlan is available for the given network.

Changed the format to the one being shown below.
Screenshot 2024-04-03 at 5 32 15 AM

**Review by alessandroargentieri — DISMISSED** [review]
LGTM

**Comment by alejandrojnm** [comment]
The new format is different from the rest of the CLI, we wanna that ??

**Comment by uzaxirr** [comment]
> The new format is different from the rest of the CLI, we wanna that ??

nope its not different, objectstore show and kubernetes show also follow the same format

**Pull request closed without merging**
