### PR TITLE
Fixed `civo kubernetes create --remove-applications` so that more than one app is removed

### PR DESCRIPTION
**Pull request by ghost**
What happens when you remove an entry in a slice while iterating over it in ascending order is that the entire slice is shifted forward. Only the first entry for `--remove-applications` will ever be removed.

My change simply iterates the iApps slice backwards, which fixes this.

@haardikdharma10 this is a bug fix.

### CODE REVIEW

**Comment by haardikdharma10** [comment]
@protosam have you tested this? I tested it locally and get the following error - 

```
$ ./civo_mac k3s create haardik --remove-applications Traefik-v2-nodeport,metrics-server
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/civo/cli/cmd.InstallApps({0xc000208300, 0x2, 0x169d0b6}, {0x0, 0x199}, {0x2064588dc, 0x16365a0})
        /Users/haardik/Desktop/civo/github/cli/cmd/kubernetes_create.go:281 +0x436
github.com/civo/cli/cmd.glob..func76(0x1f11820, {0xc0004a4e70, 0x1, 0x3})
        /Users/haardik/Desktop/civo/github/cli/cmd/kubernetes_create.go:178 +0xb25
github.com/spf13/cobra.(*Command).execute(0x1f11820, {0xc0004a4e10, 0x3, 0x3})
        /Users/haardik/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x1f15480)
        /Users/haardik/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/haardik/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/civo/cli/cmd.Execute()
        /Users/haardik/Desktop/civo/github/cli/cmd/root.go:27 +0x25
main.main()
        /Users/haardik/Desktop/civo/github/cli/main.go:23 +0x17
```

If you have tested it can you please post the result here? Also, what am I missing?

**Comment by haardikdharma10** [comment]
Actually, I ran it now with `./civo_mac k3s create haardik --remove-applications Traefik-v2-nodeport metrics-server`

It does remove `Traefik-v2-nodeport` but not `metrics server`. 

And if I run `./civo_mac k3s create haardik --remove-applications metrics-server Traefik-v2-nodeport`, it removes `metrics-server` but not `Traefik-v2-nodeport`. In both cases, it seem to remove only the first application.

**Comment by ghost** [comment]
I tested it with `go run main.go k3s create sentinel --remove-applications metrics-server,Traefik-v2-nodeport ...bunch of other flags`

Running `--remove-applications Traefik-v2-nodeport metrics-server` wont work, it has to be separated by `,`. I think this is a good opportunity to just change remove application to an array; because it's bugged anyways.

Will follow up on this.

**Comment by alejandrojnm** [comment]
you need to change the flag to an array, in that way you can iterate over the flag

**Comment by ghost** [comment]
Think I might have just gotten lucky in my prior testing with the order of the values being just right to pass without removed iApps values being accessed.

The cause was after an iApps entry was removed, it would be tested again against other removed apps. I've swapped the scope to prevent this. 

Below I show removing the two default apps. I also tested it with just metrics-server as well.
```
$ go run main.go k3s create sentinel --remove-applications metrics-server,Traefik-v2-nodeport
The cluster sentinel (c8bb83b2-43ed-4153-830f-fdf7949227fe) has been created

$ go run main.go k3s show sentinel
                    ID : c8bb83b2-43ed-4153-830f-fdf7949227fe
                  Name : sentinel
                Region : NYC1
                 Nodes : 3
                  Size : g4s.kube.medium
                Status : BUILDING
               Version : 1.22.2-k3s1
          API Endpoint : https://212.2.244.120:6443
           External IP : 212.2.244.120
          DNS A record : c8bb83b2-43ed-4153-830f-fdf7949227fe.k8s.civo.com
Installed Applications : 

Pool (f6a7f4):
+-----------------------------------------------+----+----------+-----------------+-----------+----------+---------------+
| Name                                          | IP | Status   | Size            | Cpu Cores | RAM (MB) | SSD disk (GB) |
+-----------------------------------------------+----+----------+-----------------+-----------+----------+---------------+
| k3s-sentinel-dff2-86424e-node-pool-1910-i1x6t |    | BUILDING | g4s.kube.medium |         2 |     4096 |            50 |
| k3s-sentinel-dff2-86424e-node-pool-1910-quayu |    | BUILDING | g4s.kube.medium |         2 |     4096 |            50 |
| k3s-sentinel-dff2-86424e-node-pool-1910-rep5y |    | BUILDING | g4s.kube.medium |         2 |     4096 |            50 |
+-----------------------------------------------+----+----------+-----------------+-----------+----------+---------------+

Labels:
kubernetes.civo.com/node-pool=f6a7f406-5c5e-4ed3-b687-a86c0f417e4f
kubernetes.civo.com/node-size=g4s.kube.medium
```


@alejandrojnm after thinking about this a bit, since `--applications` still uses a comma separated value, I've determined to leave `--remove-applications` as-is for consistency.

**Pull request closed without merging**
