### PR TITLE
Updated README.md 

### PR DESCRIPTION
**Pull request by Arijit1000**
Added Load Balancer Docs File. Mentioned about how to use Load Balancer CLI commands, uses of load balancing, and how Kubernetes handles load balancing. Also mentioned a couple of key components of Kubernetes load balancing.

### CODE REVIEW

**Comment by Arijit1000** [comment]
Hello @haardikdharma10  Could you please review this PR?

**Comment by haardikdharma10** [comment]
I'll defer to @kaihoffman to review the docs. Kai, can you take a look at your convenience?

**Comment by kaihoffman** [comment]
I think while the context for how Kubernetes handles load balancing, for brevity's sake it would be good to have the README only have the Civo-specific implementation and main commands detailed. @Arijit1000 would you be willing to trim this down, but keeping the material you've written on file? I have an upcoming future open source thing I think it might be useful to add to.

**Comment by Arijit1000** [comment]
@kaihoffman Surely, I will brief up this and will focus on Civo-specific implementation.

**Comment by haardikdharma10** [comment]
Closing due to inactivity. Please reopen if needed.

**Pull request closed without merging**
